vim.g.mapleader = ";"
vim.g.maplocalleader = "\\"
vim.opt.number = true -- Print the line number in front of each line
vim.opt.relativenumber = true -- Show the line number relative to the line with t
vim.o.signcolumn = "yes:1"
vim.o.numberwidth = 3
vim.opt.ruler = true -- Show the line and column number of the cursor position, separated by a comma.o
vim.opt.showmatch = true -- When a bracket is inserted, briefly jump to the matc
vim.opt.title = true -- When on, the title of the window will be set to the value of 'titlestring'
vim.opt.swapfile = false -- disable swapfiles
vim.opt.shiftwidth = 4
vim.opt.tabstop = 4
